### ISSUE TITLE
Dominando o Android 2ª edição (Alarme)

### ISSUE THREAD

**Issue by nerdizim** [nglauber/nglauberapp#2]
Olá comprei o livro Dominando o Android 2ª edição e estou gostando bastante, gosto de estudar por conta própria e estou de fato aprendendo muito. No capítulo 
![alarme](https://user-images.githubusercontent.com/26264374/39144609-a427e4bc-4707-11e8-90c1-c3fd78c6279f.png)
sobre Intentes implícitas vi como usar AlarmClock.... pág 86. Ai tive a ideia de criar meu calendário. Porem me perdi com o seguinte:

O usuário clica no(os) botão(ões) correspondente ao dia, coloca a hora e os minutos aperta em salvar. Porem não consigo usar o botão correspondente ao dia para usar no AlarmClock. 
Exemplo btnDomingo(Calendar.SUNDAY)

Obrigado pela ajuda!

**Comment by nglauber** [comment]
Oi Cassio,
Eu respondi o seu email. As issues são para reportar problemas no código de exemplo do livro.
Então vou fechar essa aqui.
